/**
 * Seed data for the BDJobs AI marketplace.
 * All names are unique Bangladeshi names with no duplicates across entities.
 * Salary ranges in BDT: entry 15000-30000, mid 30000-60000, senior 60000-120000.
 */

import {
  MALE_NAMES,
  FEMALE_NAMES,
  COMPANY_NAMES,
  LOCATIONS,
  INDUSTRIES,
} from './names'

// Pre-defined UUIDs for referential integrity
export const USER_IDS = {
  jobseekers: [
    'a1b2c3d4-1111-4000-8000-000000000001',
    'a1b2c3d4-1111-4000-8000-000000000002',
    'a1b2c3d4-1111-4000-8000-000000000003',
    'a1b2c3d4-1111-4000-8000-000000000004',
    'a1b2c3d4-1111-4000-8000-000000000005',
    'a1b2c3d4-1111-4000-8000-000000000006',
    'a1b2c3d4-1111-4000-8000-000000000007',
    'a1b2c3d4-1111-4000-8000-000000000008',
    'a1b2c3d4-1111-4000-8000-000000000009',
    'a1b2c3d4-1111-4000-8000-000000000010',
  ],
  employers: [
    'b2c3d4e5-2222-4000-8000-000000000001',
    'b2c3d4e5-2222-4000-8000-000000000002',
    'b2c3d4e5-2222-4000-8000-000000000003',
    'b2c3d4e5-2222-4000-8000-000000000004',
    'b2c3d4e5-2222-4000-8000-000000000005',
  ],
} as const

export const COMPANY_IDS = [
  'c3d4e5f6-3333-4000-8000-000000000001',
  'c3d4e5f6-3333-4000-8000-000000000002',
  'c3d4e5f6-3333-4000-8000-000000000003',
  'c3d4e5f6-3333-4000-8000-000000000004',
  'c3d4e5f6-3333-4000-8000-000000000005',
] as const

export const JOB_IDS = [
  'd4e5f6a7-4444-4000-8000-000000000001',
  'd4e5f6a7-4444-4000-8000-000000000002',
  'd4e5f6a7-4444-4000-8000-000000000003',
  'd4e5f6a7-4444-4000-8000-000000000004',
  'd4e5f6a7-4444-4000-8000-000000000005',
  'd4e5f6a7-4444-4000-8000-000000000006',
  'd4e5f6a7-4444-4000-8000-000000000007',
  'd4e5f6a7-4444-4000-8000-000000000008',
  'd4e5f6a7-4444-4000-8000-000000000009',
  'd4e5f6a7-4444-4000-8000-000000000010',
  'd4e5f6a7-4444-4000-8000-000000000011',
  'd4e5f6a7-4444-4000-8000-000000000012',
  'd4e5f6a7-4444-4000-8000-000000000013',
  'd4e5f6a7-4444-4000-8000-000000000014',
  'd4e5f6a7-4444-4000-8000-000000000015',
] as const

export interface SeedJobseeker {
  id: string
  email: string
  full_name: string
  role: 'jobseeker'
  phone: string
  location: string
  bio: string
  degree: string
  degree_field: string
  experience_years: number
  skills: string[]
  languages: string[]
  preferred_job_categories: string[]
}

export interface SeedEmployer {
  id: string
  email: string
  full_name: string
  role: 'employer'
  phone: string
  location: string
  bio: string
}

export interface SeedCompany {
  id: string
  owner_id: string
  name: string
  description: string
  industry: string
  location: string
  website: string
}

export interface SeedJob {
  id: string
  company_id: string
  title: string
  description: string
  requirements: string
  required_skills: string[]
  preferred_skills: string[]
  degree_requirement: string
  experience_min: number
  experience_max: number
  job_category: string
  location: string
  salary_min: number
  salary_max: number
  employment_type: 'full-time' | 'part-time' | 'contract' | 'internship'
}

export const SEED_JOBSEEKERS: SeedJobseeker[] = [
  {
    id: USER_IDS.jobseekers[0],
    email: 'rafiq.ahmed@example.com',
    full_name: MALE_NAMES[0],
    role: 'jobseeker',
    phone: '+8801711000001',
    location: LOCATIONS[0],
    bio: 'Experienced full-stack developer with expertise in React and Node.js',
    degree: 'bachelors',
    degree_field: 'Computer Science',
    experience_years: 4,
    skills: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'PostgreSQL', 'Docker'],
    languages: ['Bengali', 'English'],
    preferred_job_categories: ['software-engineering', 'web-development'],
  },
  {
    id: USER_IDS.jobseekers[1],
    email: 'fatema.akter@example.com',
    full_name: FEMALE_NAMES[0],
    role: 'jobseeker',
    phone: '+8801711000002',
    location: LOCATIONS[1],
    bio: 'Data science enthusiast with strong Python and ML background',
    degree: 'masters',
    degree_field: 'Data Science',
    experience_years: 3,
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'SQL', 'Pandas', 'R'],
    languages: ['Bengali', 'English', 'Hindi'],
    preferred_job_categories: ['data-science', 'software-engineering'],
  },
  {
    id: USER_IDS.jobseekers[2],
    email: 'kamal.hossain@example.com',
    full_name: MALE_NAMES[1],
    role: 'jobseeker',
    phone: '+8801711000003',
    location: LOCATIONS[2],
    bio: 'Fresh graduate passionate about mobile app development',
    degree: 'bachelors',
    degree_field: 'Software Engineering',
    experience_years: 1,
    skills: ['Flutter', 'Dart', 'Firebase', 'Java', 'Android'],
    languages: ['Bengali', 'English'],
    preferred_job_categories: ['mobile-development', 'software-engineering'],
  },
  {
    id: USER_IDS.jobseekers[3],
    email: 'nusrat.jahan@example.com',
    full_name: FEMALE_NAMES[1],
    role: 'jobseeker',
    phone: '+8801711000004',
    location: LOCATIONS[0],
    bio: 'UI/UX designer with 5+ years creating digital experiences',
    degree: 'bachelors',
    degree_field: 'Graphic Design',
    experience_years: 6,
    skills: ['Figma', 'Adobe XD', 'Sketch', 'HTML', 'CSS', 'User Research'],
    languages: ['Bengali', 'English'],
    preferred_job_categories: ['ui-ux-design', 'graphic-design'],
  },
  {
    id: USER_IDS.jobseekers[4],
    email: 'tariq.rahman@example.com',
    full_name: MALE_NAMES[2],
    role: 'jobseeker',
    phone: '+8801711000005',
    location: LOCATIONS[3],
    bio: 'DevOps engineer specializing in cloud infrastructure and CI/CD',
    degree: 'bachelors',
    degree_field: 'Computer Engineering',
    experience_years: 5,
    skills: ['AWS', 'Kubernetes', 'Docker', 'Terraform', 'Linux', 'Jenkins', 'Python'],
    languages: ['Bengali', 'English'],
    preferred_job_categories: ['devops', 'software-engineering'],
  },
  {
    id: USER_IDS.jobseekers[5],
    email: 'tahmina.sultana@example.com',
    full_name: FEMALE_NAMES[2],
    role: 'jobseeker',
    phone: '+8801711000006',
    location: LOCATIONS[4],
    bio: 'Digital marketing specialist with expertise in SEO and content strategy',
    degree: 'bachelors',
    degree_field: 'Marketing',
    experience_years: 3,
    skills: ['SEO', 'Google Analytics', 'Social Media Marketing', 'Content Strategy', 'Copywriting'],
    languages: ['Bengali', 'English'],
    preferred_job_categories: ['digital-marketing', 'marketing'],
  },
  {
    id: USER_IDS.jobseekers[6],
    email: 'nazmul.islam@example.com',
    full_name: MALE_NAMES[3],
    role: 'jobseeker',
    phone: '+8801711000007',
    location: LOCATIONS[5],
    bio: 'Cybersecurity analyst with experience in penetration testing',
    degree: 'masters',
    degree_field: 'Cybersecurity',
    experience_years: 4,
    skills: ['Network Security', 'Penetration Testing', 'SIEM', 'Python', 'Linux', 'Wireshark'],
    languages: ['Bengali', 'English'],
    preferred_job_categories: ['cybersecurity', 'it-support'],
  },
  {
    id: USER_IDS.jobseekers[7],
    email: 'sharmin.nahar@example.com',
    full_name: FEMALE_NAMES[3],
    role: 'jobseeker',
    phone: '+8801711000008',
    location: LOCATIONS[0],
    bio: 'Recent commerce graduate looking for finance and accounting roles',
    degree: 'bachelors',
    degree_field: 'Commerce',
    experience_years: 0,
    skills: ['Excel', 'Financial Analysis', 'QuickBooks', 'Tally'],
    languages: ['Bengali', 'English'],
    preferred_job_categories: ['accounting', 'finance'],
  },
  {
    id: USER_IDS.jobseekers[8],
    email: 'ashraful.alam@example.com',
    full_name: MALE_NAMES[4],
    role: 'jobseeker',
    phone: '+8801711000009',
    location: LOCATIONS[6],
    bio: 'Project manager with PMP certification and Agile expertise',
    degree: 'masters',
    degree_field: 'Business Administration',
    experience_years: 8,
    skills: ['Agile', 'Scrum', 'JIRA', 'MS Project', 'Stakeholder Management', 'Risk Management'],
    languages: ['Bengali', 'English', 'Arabic'],
    preferred_job_categories: ['project-management', 'operations'],
  },
  {
    id: USER_IDS.jobseekers[9],
    email: 'afsana.mimi@example.com',
    full_name: FEMALE_NAMES[4],
    role: 'jobseeker',
    phone: '+8801711000010',
    location: LOCATIONS[7],
    bio: 'Backend developer experienced in microservices and system design',
    degree: 'bachelors',
    degree_field: 'Information Technology',
    experience_years: 3,
    skills: ['Java', 'Spring Boot', 'Microservices', 'PostgreSQL', 'Redis', 'RabbitMQ'],
    languages: ['Bengali', 'English'],
    preferred_job_categories: ['software-engineering', 'web-development'],
  },
]

export const SEED_EMPLOYERS: SeedEmployer[] = [
  {
    id: USER_IDS.employers[0],
    email: 'mizanur.haque@techventures.example.com',
    full_name: MALE_NAMES[5],
    role: 'employer',
    phone: '+8801811000001',
    location: LOCATIONS[0],
    bio: 'CEO at TechVentures Bangladesh, building the future of tech',
  },
  {
    id: USER_IDS.employers[1],
    email: 'rabeya.khatun@datasoft.example.com',
    full_name: FEMALE_NAMES[5],
    role: 'employer',
    phone: '+8801811000002',
    location: LOCATIONS[0],
    bio: 'HR Director at DataSoft Systems with 10 years in tech recruitment',
  },
  {
    id: USER_IDS.employers[2],
    email: 'shahin.mridha@greendelta.example.com',
    full_name: MALE_NAMES[6],
    role: 'employer',
    phone: '+8801811000003',
    location: LOCATIONS[1],
    bio: 'Founder of GreenDelta Solutions, focused on sustainable tech',
  },
  {
    id: USER_IDS.employers[3],
    email: 'dilruba.yasmin@pathao.example.com',
    full_name: FEMALE_NAMES[6],
    role: 'employer',
    phone: '+8801811000004',
    location: LOCATIONS[0],
    bio: 'Talent Acquisition Lead at Pathao Technologies',
  },
  {
    id: USER_IDS.employers[4],
    email: 'jahangir.kabir@chaldal.example.com',
    full_name: MALE_NAMES[7],
    role: 'employer',
    phone: '+8801811000005',
    location: LOCATIONS[0],
    bio: 'CTO at Chaldal Engineering, scaling e-commerce platforms',
  },
]

export const SEED_COMPANIES: SeedCompany[] = [
  {
    id: COMPANY_IDS[0],
    owner_id: USER_IDS.employers[0],
    name: COMPANY_NAMES[0],
    description: 'Leading technology company building innovative solutions for Bangladesh and beyond. We specialize in enterprise software and AI-driven products.',
    industry: INDUSTRIES[0],
    location: LOCATIONS[0],
    website: 'https://techventures.example.com',
  },
  {
    id: COMPANY_IDS[1],
    owner_id: USER_IDS.employers[1],
    name: COMPANY_NAMES[1],
    description: 'Premier software development firm delivering cutting-edge data solutions and business intelligence platforms.',
    industry: INDUSTRIES[9],
    location: LOCATIONS[0],
    website: 'https://datasoft.example.com',
  },
  {
    id: COMPANY_IDS[2],
    owner_id: USER_IDS.employers[2],
    name: COMPANY_NAMES[2],
    description: 'Sustainable technology solutions provider focused on green energy and environmental monitoring systems.',
    industry: INDUSTRIES[0],
    location: LOCATIONS[1],
    website: 'https://greendelta.example.com',
  },
  {
    id: COMPANY_IDS[3],
    owner_id: USER_IDS.employers[3],
    name: COMPANY_NAMES[3],
    description: 'Bangladesh\'s leading ride-sharing and logistics technology company, connecting millions of users daily.',
    industry: INDUSTRIES[6],
    location: LOCATIONS[0],
    website: 'https://pathao.example.com',
  },
  {
    id: COMPANY_IDS[4],
    owner_id: USER_IDS.employers[4],
    name: COMPANY_NAMES[4],
    description: 'E-commerce technology company revolutionizing online grocery delivery in Bangladesh with advanced logistics.',
    industry: INDUSTRIES[2],
    location: LOCATIONS[0],
    website: 'https://chaldal.example.com',
  },
]

export const SEED_JOBS: SeedJob[] = [
  {
    id: JOB_IDS[0],
    company_id: COMPANY_IDS[0],
    title: 'Senior Full-Stack Developer',
    description: 'We are looking for a Senior Full-Stack Developer to join our core platform team. You will be responsible for building scalable web applications using modern frameworks.',
    requirements: 'Strong experience with React, Node.js, and PostgreSQL. Must have experience with microservices architecture.',
    required_skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL'],
    preferred_skills: ['Docker', 'AWS', 'GraphQL'],
    degree_requirement: 'bachelors',
    experience_min: 4,
    experience_max: 8,
    job_category: 'software-engineering',
    location: LOCATIONS[0],
    salary_min: 60000,
    salary_max: 120000,
    employment_type: 'full-time',
  },
  {
    id: JOB_IDS[1],
    company_id: COMPANY_IDS[0],
    title: 'Junior Frontend Developer',
    description: 'Join our growing team as a Junior Frontend Developer. Work on exciting UI projects with mentorship from senior engineers.',
    requirements: 'Basic knowledge of React and CSS. Eagerness to learn and grow.',
    required_skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    preferred_skills: ['TypeScript', 'Tailwind CSS'],
    degree_requirement: 'bachelors',
    experience_min: 0,
    experience_max: 2,
    job_category: 'web-development',
    location: LOCATIONS[0],
    salary_min: 15000,
    salary_max: 30000,
    employment_type: 'full-time',
  },
  {
    id: JOB_IDS[2],
    company_id: COMPANY_IDS[1],
    title: 'Data Scientist',
    description: 'Looking for a talented Data Scientist to build predictive models and derive insights from large datasets.',
    requirements: 'Strong background in statistics, machine learning, and Python programming.',
    required_skills: ['Python', 'Machine Learning', 'SQL', 'TensorFlow'],
    preferred_skills: ['Deep Learning', 'NLP', 'Spark'],
    degree_requirement: 'masters',
    experience_min: 2,
    experience_max: 5,
    job_category: 'data-science',
    location: LOCATIONS[0],
    salary_min: 50000,
    salary_max: 90000,
    employment_type: 'full-time',
  },
  {
    id: JOB_IDS[3],
    company_id: COMPANY_IDS[1],
    title: 'Database Administrator',
    description: 'Manage and optimize our database infrastructure. Ensure high availability and performance of critical data systems.',
    requirements: 'Experience with PostgreSQL, MySQL, and database optimization techniques.',
    required_skills: ['PostgreSQL', 'MySQL', 'Database Optimization', 'Linux'],
    preferred_skills: ['MongoDB', 'Redis', 'Cloud Databases'],
    degree_requirement: 'bachelors',
    experience_min: 3,
    experience_max: 7,
    job_category: 'it-support',
    location: LOCATIONS[0],
    salary_min: 45000,
    salary_max: 80000,
    employment_type: 'full-time',
  },
  {
    id: JOB_IDS[4],
    company_id: COMPANY_IDS[2],
    title: 'Mobile App Developer',
    description: 'Build cross-platform mobile applications for our environmental monitoring solutions using Flutter.',
    requirements: 'Experience with Flutter/Dart and mobile app deployment to app stores.',
    required_skills: ['Flutter', 'Dart', 'Firebase', 'REST APIs'],
    preferred_skills: ['iOS', 'Android', 'CI/CD'],
    degree_requirement: 'bachelors',
    experience_min: 1,
    experience_max: 4,
    job_category: 'mobile-development',
    location: LOCATIONS[1],
    salary_min: 30000,
    salary_max: 55000,
    employment_type: 'full-time',
  },
  {
    id: JOB_IDS[5],
    company_id: COMPANY_IDS[2],
    title: 'UI/UX Designer',
    description: 'Design intuitive interfaces for our web and mobile applications. Conduct user research and create prototypes.',
    requirements: 'Proficiency in Figma or Sketch. Portfolio demonstrating strong design skills.',
    required_skills: ['Figma', 'User Research', 'Prototyping', 'UI Design'],
    preferred_skills: ['Adobe XD', 'Illustration', 'Motion Design'],
    degree_requirement: 'bachelors',
    experience_min: 2,
    experience_max: 6,
    job_category: 'ui-ux-design',
    location: LOCATIONS[1],
    salary_min: 35000,
    salary_max: 60000,
    employment_type: 'full-time',
  },
  {
    id: JOB_IDS[6],
    company_id: COMPANY_IDS[3],
    title: 'DevOps Engineer',
    description: 'Join our infrastructure team to build and maintain CI/CD pipelines, manage cloud resources, and ensure system reliability.',
    requirements: 'Strong experience with AWS, Kubernetes, and infrastructure as code.',
    required_skills: ['AWS', 'Kubernetes', 'Docker', 'Terraform'],
    preferred_skills: ['Ansible', 'Prometheus', 'Grafana'],
    degree_requirement: 'bachelors',
    experience_min: 3,
    experience_max: 7,
    job_category: 'devops',
    location: LOCATIONS[0],
    salary_min: 55000,
    salary_max: 100000,
    employment_type: 'full-time',
  },
  {
    id: JOB_IDS[7],
    company_id: COMPANY_IDS[3],
    title: 'Digital Marketing Manager',
    description: 'Lead our digital marketing initiatives including SEO, SEM, social media campaigns, and performance marketing.',
    requirements: 'Proven track record in digital marketing with measurable results.',
    required_skills: ['SEO', 'Google Ads', 'Social Media Marketing', 'Analytics'],
    preferred_skills: ['Content Strategy', 'Email Marketing', 'A/B Testing'],
    degree_requirement: 'bachelors',
    experience_min: 3,
    experience_max: 6,
    job_category: 'digital-marketing',
    location: LOCATIONS[0],
    salary_min: 40000,
    salary_max: 70000,
    employment_type: 'full-time',
  },
  {
    id: JOB_IDS[8],
    company_id: COMPANY_IDS[3],
    title: 'Cybersecurity Analyst',
    description: 'Protect our systems and user data from security threats. Perform vulnerability assessments and implement security protocols.',
    requirements: 'Experience in network security, threat analysis, and security compliance.',
    required_skills: ['Network Security', 'SIEM', 'Vulnerability Assessment', 'Python'],
    preferred_skills: ['Penetration Testing', 'SOC Operations', 'ISO 27001'],
    degree_requirement: 'bachelors',
    experience_min: 2,
    experience_max: 5,
    job_category: 'cybersecurity',
    location: LOCATIONS[0],
    salary_min: 45000,
    salary_max: 80000,
    employment_type: 'full-time',
  },
  {
    id: JOB_IDS[9],
    company_id: COMPANY_IDS[4],
    title: 'Backend Engineer',
    description: 'Build robust backend services for our e-commerce platform handling millions of daily orders.',
    requirements: 'Strong experience with Java/Spring Boot or Node.js. Understanding of distributed systems.',
    required_skills: ['Java', 'Spring Boot', 'Microservices', 'PostgreSQL'],
    preferred_skills: ['Redis', 'Kafka', 'Elasticsearch'],
    degree_requirement: 'bachelors',
    experience_min: 2,
    experience_max: 5,
    job_category: 'software-engineering',
    location: LOCATIONS[0],
    salary_min: 40000,
    salary_max: 75000,
    employment_type: 'full-time',
  },
  {
    id: JOB_IDS[10],
    company_id: COMPANY_IDS[4],
    title: 'Project Manager',
    description: 'Manage cross-functional projects from inception to delivery. Coordinate between engineering, product, and business teams.',
    requirements: 'PMP or equivalent certification preferred. Experience with Agile methodologies.',
    required_skills: ['Agile', 'Scrum', 'JIRA', 'Stakeholder Management'],
    preferred_skills: ['PMP', 'Risk Management', 'Budget Management'],
    degree_requirement: 'bachelors',
    experience_min: 5,
    experience_max: 10,
    job_category: 'project-management',
    location: LOCATIONS[0],
    salary_min: 60000,
    salary_max: 110000,
    employment_type: 'full-time',
  },
  {
    id: JOB_IDS[11],
    company_id: COMPANY_IDS[0],
    title: 'QA Engineer Intern',
    description: 'Learn quality assurance practices while testing our web and mobile applications. Great opportunity for fresh graduates.',
    requirements: 'Basic understanding of software testing concepts. Attention to detail.',
    required_skills: ['Manual Testing', 'Bug Reporting', 'Test Cases'],
    preferred_skills: ['Selenium', 'JIRA', 'API Testing'],
    degree_requirement: 'bachelors',
    experience_min: 0,
    experience_max: 1,
    job_category: 'software-engineering',
    location: LOCATIONS[0],
    salary_min: 15000,
    salary_max: 20000,
    employment_type: 'internship',
  },
  {
    id: JOB_IDS[12],
    company_id: COMPANY_IDS[2],
    title: 'Content Writer',
    description: 'Create engaging content for our blog, social media, and marketing materials about environmental technology.',
    requirements: 'Excellent writing skills in English and Bengali. Understanding of SEO principles.',
    required_skills: ['Content Writing', 'SEO', 'Social Media', 'Research'],
    preferred_skills: ['WordPress', 'Copywriting', 'Video Scripts'],
    degree_requirement: 'bachelors',
    experience_min: 1,
    experience_max: 3,
    job_category: 'content-writing',
    location: LOCATIONS[1],
    salary_min: 20000,
    salary_max: 35000,
    employment_type: 'full-time',
  },
  {
    id: JOB_IDS[13],
    company_id: COMPANY_IDS[4],
    title: 'Part-time Accounting Assistant',
    description: 'Assist with day-to-day accounting tasks including invoice processing, reconciliation, and financial reporting.',
    requirements: 'Degree in Commerce or Accounting. Proficiency in Excel and accounting software.',
    required_skills: ['Excel', 'Financial Analysis', 'Accounting', 'QuickBooks'],
    preferred_skills: ['Tally', 'SAP', 'Tax Filing'],
    degree_requirement: 'bachelors',
    experience_min: 0,
    experience_max: 2,
    job_category: 'accounting',
    location: LOCATIONS[0],
    salary_min: 15000,
    salary_max: 25000,
    employment_type: 'part-time',
  },
  {
    id: JOB_IDS[14],
    company_id: COMPANY_IDS[3],
    title: 'React Native Developer',
    description: 'Develop and maintain our rider and driver mobile applications built with React Native.',
    requirements: 'Experience building production React Native apps. Understanding of mobile performance optimization.',
    required_skills: ['React Native', 'JavaScript', 'TypeScript', 'Mobile Development'],
    preferred_skills: ['Redux', 'GraphQL', 'App Store Deployment'],
    degree_requirement: 'bachelors',
    experience_min: 2,
    experience_max: 5,
    job_category: 'mobile-development',
    location: LOCATIONS[0],
    salary_min: 40000,
    salary_max: 70000,
    employment_type: 'full-time',
  },
]
